# Generated by Django 4.0.6 on 2022-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200419_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=654173, unique=True),
        ),
    ]
